from . import scholar_scholarship
from . import scholarship_campus 
from . import scholarship_category 
from . import scholarship_class 
from . import scholarship_section 
from . import scholarship_staff_category
from . import scholarship_lines
from . import scholarship_stages
from . import scholarship_tags
from . import scholar_ship_lines_remarks
from . import res_partner
from . import donor_sub_group