name: Deploy and Restart 180-web1-1 Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Ensure repo is initialized
        run: |
          echo "Pulling Changes..."
          REPO_URL=git@github.com:itsosamanadeem/aa-associate.git
          cd ~/demo1_odoo_instance/18.0/custom-addons
          git pull origin main

      - name: Restart Docker container 180-web1-1
        run: |
          echo "Restarting Docker container..."
          docker restart 180-web1-1
